zuul:
  ignoredServices: "*"
  prefix: /api
  routes:
    productcomposite: /product/**

  
server:
  port: 8080

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 3
    preferIpAddress: true
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
  client:
    # Default values comes from org.springframework.cloud.netflix.eurek.EurekaClientConfigBean
    registryFetchIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5
    initialInstanceInfoReplicationIntervalSeconds: 5
